package cd

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *KV) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "d":
			z.Data, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Data")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z KV) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "d"
	err = en.Append(0x81, 0xa1, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.Data)
	if err != nil {
		err = msgp.WrapError(err, "Data")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z KV) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "d"
	o = append(o, 0x81, 0xa1, 0x64)
	o = msgp.AppendString(o, z.Data)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *KV) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "d":
			z.Data, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Data")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z KV) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len(z.Data)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Lock) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "o":
			z.Handle, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Handle")
				return
			}
		case "t":
			z.Till, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Till")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Lock) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "o"
	err = en.Append(0x82, 0xa1, 0x6f)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Handle)
	if err != nil {
		err = msgp.WrapError(err, "Handle")
		return
	}
	// write "t"
	err = en.Append(0xa1, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Till)
	if err != nil {
		err = msgp.WrapError(err, "Till")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Lock) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "o"
	o = append(o, 0x82, 0xa1, 0x6f)
	o = msgp.AppendInt64(o, z.Handle)
	// string "t"
	o = append(o, 0xa1, 0x74)
	o = msgp.AppendInt64(o, z.Till)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Lock) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "o":
			z.Handle, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Handle")
				return
			}
		case "t":
			z.Till, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Till")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Lock) Msgsize() (s int) {
	s = 1 + 2 + msgp.Int64Size + 2 + msgp.Int64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *QueueMeta) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Front":
			z.Front, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Front")
				return
			}
		case "Back":
			z.Back, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Back")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z QueueMeta) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Front"
	err = en.Append(0x82, 0xa5, 0x46, 0x72, 0x6f, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Front)
	if err != nil {
		err = msgp.WrapError(err, "Front")
		return
	}
	// write "Back"
	err = en.Append(0xa4, 0x42, 0x61, 0x63, 0x6b)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Back)
	if err != nil {
		err = msgp.WrapError(err, "Back")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z QueueMeta) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Front"
	o = append(o, 0x82, 0xa5, 0x46, 0x72, 0x6f, 0x6e, 0x74)
	o = msgp.AppendInt64(o, z.Front)
	// string "Back"
	o = append(o, 0xa4, 0x42, 0x61, 0x63, 0x6b)
	o = msgp.AppendInt64(o, z.Back)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *QueueMeta) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Front":
			z.Front, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Front")
				return
			}
		case "Back":
			z.Back, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Back")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z QueueMeta) Msgsize() (s int) {
	s = 1 + 6 + msgp.Int64Size + 5 + msgp.Int64Size
	return
}
